[workspace]
members = [
"solana-esp-sdk",
"examples/esp32s3-demo",
]
resolver = "2"


[workspace.package]
edition = "2021"
license = "Apache-2.0"


[workspace.dependencies]
# Centralised versions for crates currently used by the SDK
solana-program = { version = "1.18", default-features = false }
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
ed25519-compact = "2.1.1"
rand_core = { version = "0.6", default-features = false }