[workspace]
members = [
"crates/solana-esp-sdk",
"examples/host-demo",
"examples/esp32s3-demo",
]
resolver = "2"


[workspace.package]
edition = "2021"
license = "Apache-2.0"


[workspace.dependencies]
# Centralised versions (tweak as needed)
solana-program = { version = "1.18", default-features = false }
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
ed25519-compact = { version = "2"}
rand_core = { version = "0.6", default-features = false }
heapless = "0.8"
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1"}
thiserror = { version = "1", default-features = false }