[package]
name = "host-demo"
version = "0.1.0"
edition = "2021"


[dependencies]
solana-esp-sdk = { path = "../../crates/solana-esp-sdk", features = ["std"] }
ureq = { version = "2" }
bs58 = "0.5"
rand = { version = "0.8", features = ["std_rng"] }